name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      tfvars_file:
        description: 'Path to the tfvars file'
        required: true
        default: 'variables.tfvars'
      action:
        type: choice
        description: 'Terraform Action (plan/apply/destroy)'
        options:
          - plan
          - apply
          - destroy
        required: true
        default: 'plan'

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

permissions:
  contents: read

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./eks
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

  setup-terraform:
    runs-on: ubuntu-latest
    needs: checkout-repo
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with: 
        terraform_version: 1.8.4

  terraform-initialize:
    runs-on: ubuntu-latest
    needs: setup-terraform
    steps:
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Validate
      run: terraform validate

  terraform-action:
    runs-on: ubuntu-latest
    needs: terraform-initialize
    steps:
    - name: Terraform Plan
      if: ${{ github.event.inputs.action == 'plan' }}
      run: terraform plan -var-file=./eks/${{ github.event.inputs.tfvars_file }} -input=false
    
    - name: Terraform Apply
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform apply -var-file=./eks/${{ github.event.inputs.tfvars_file }} -input=false -auto-approve
    
    - name: Terraform Destroy
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: terraform destroy -var-file=./eks/${{ github.event.inputs.tfvars_file }} -input=false -auto-approve
