name: 'Terraform'

on:
    workflow_dispatch:
        inputs:
            tfvars_file:
                description: 'Path to the tfvars file'
                required: true
                default: 'variables.tfvars'
            action:
                type: choice
                description: 'Apply or Destroy'
                options:
                - plan
                - apply
                - destroy
                required: true
                default: 'apply'
env:
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
    
permissions:
    contents: read

jobs:
    checkout-repo:
        runs-on: ubuntu-latest
        environment: production
        defaults:
            run:
                shell: bash
                working-directory: eks
        env:
            AWS_REGION: us-east-1
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        steps:
        - name: Checkout
            uses: actions/checkout@v4

    
    setting-up-terraform:
        runs-on: ubuntu-latest
        needs: checkout-repo
        steps:
        - name: Setup Terraform
            uses: hashicorp/setup-terraform@v1
            with: 
            terraform_version: 1.8.4

    Terraform-Initializing:
        runs-on: ubuntu-latest
        needs: setting-up-terraform
        steps:  
        - name: Setup Terraform
            uses: hashicorp/setup-terraform@v1
            with:
            terraform_version: 1.8.4  

        - name: Checkout repository
            uses: actions/checkout@v4

        - name: Terraform init
            working-directory: eks
            run: terraform init
        
        # Checks that all Terraform configuration files adhere to a canonical format
        - name: Terraform Format
            working-directory: eks
            run: terraform fmt

        - name: Terraform Validate
            working-directory: eks
            run: terraform validate

    Terraform-Action:
        runs-on: ubuntu-latest
        needs: Terraform-Initializing
        steps:
        - name: Checkout repository
            uses: actions/checkout@v4
        
        - name: Setup Terraform
            uses: hashicorp/setup-terraform@v1
            with:
            terraform_version: 1.8.4
    
        - name: Terraform Init
            working-directory: eks
            run: terraform init
        
        - name: Terraform Plan
            if: ${{ github.event.inputs.action  == 'plan' }}
            working-directory: eks
            # Generates an execution plan for Terraform
            run: |
            terraform plan -var-file=${{ github.event.inputs.tfvars_file }} -input=false

        

              
